// Code generated by hostgen. DO NOT EDIT.
//
// This file contains client wrappers for the List host service.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package main

import (
	"encoding/json"

	"github.com/extism/go-pdk"
)

// list_items is the host function provided by Navidrome.
//
//go:wasmimport extism:host/user list_items
func list_items(uint64) uint64

// ListItemsRequest is the request type for List.Items.
type ListItemsRequest struct {
	Name   string `json:"name"`
	Filter Filter `json:"filter"`
}

// ListItemsResponse is the response type for List.Items.
type ListItemsResponse struct {
	Count int32  `json:"count,omitempty"`
	Error string `json:"error,omitempty"`
}

// ListItems calls the list_items host function.
func ListItems(name string, filter Filter) (*ListItemsResponse, error) {
	// Marshal request to JSON
	req := ListItemsRequest{
		Name:   name,
		Filter: filter,
	}
	reqBytes, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}
	reqMem := pdk.AllocateBytes(reqBytes)
	defer reqMem.Free()

	// Call the host function
	responsePtr := list_items(reqMem.Offset())

	// Read the response from memory
	responseMem := pdk.FindMemory(responsePtr)
	responseBytes := responseMem.ReadBytes()

	// Parse the response
	var response ListItemsResponse
	if err := json.Unmarshal(responseBytes, &response); err != nil {
		return nil, err
	}

	return &response, nil
}
