run:
  go: "1.20"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "(G501|G401|G505):"
