# GoReleaser config
project_name: navidrome

builds:
  - id: navidrome_linux_amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=netgo
    ldflags:
      - "-extldflags '-static -lz'"
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_linux_386
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_PATH=/i386/lib/pkgconfig
    goos:
      - linux
    goarch:
      - "386"
    flags:
      - -tags=netgo
    ldflags:
      - "-extldflags '-static'"
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_linux_arm
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc
      - CXX=arm-linux-gnueabi-g++
      - PKG_CONFIG_PATH=/arm/lib/pkgconfig
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "5"
      - "6"
      - "7"
    flags:
      - -tags=netgo
    ldflags:
      - "-extldflags '-static'"
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_linux_arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - PKG_CONFIG_PATH=/arm64/lib/pkgconfig
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=netgo
    ldflags:
      - "-extldflags '-static'"
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_windows_386
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
      - PKG_CONFIG_PATH=/mingw32/lib/pkgconfig
    goos:
      - windows
    goarch:
      - "386"
    flags:
      - -tags=netgo
    ldflags:
      - "-extldflags '-static'"
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_windows_amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - PKG_CONFIG_PATH=/mingw64/lib/pkgconfig
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=netgo
    ldflags:
      - "-extldflags '-static'"
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_darwin_amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
      - PKG_CONFIG_PATH=/darwin/lib/pkgconfig
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=netgo
    ldflags:
      - -s -w -X github.com/navidrome/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/navidrome/navidrome/consts.gitTag={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

release:
  draft: true

nfpms:
  - id: navidrome
    package_name: navidrome

    homepage: https://navidrome.org
    description: |-
      🎧☁ Modern Music Server and Streamer compatible with Subsonic/Airsonic

    maintainer: Deluan Quintão <deluan at navidrome.org>

    license: GPL-3.0
    formats:
      - deb
      - rpm
      - archlinux

    dependencies:
      - ffmpeg

    suggests:
      - mpv

    overrides:
      rpm:
        dependencies:
          - "(ffmpeg or ffmpeg-free)"

    contents:
      - src: contrib/navidrome.service
        dst: /lib/systemd/system/navidrome.service
        file_info:
          mode: 0644
          owner: navidrome
          group: navidrome

      - src: contrib/navidrome.toml
        dst: /etc/navidrome/navidrome.toml
        type: "config|noreplace"
        file_info:
          mode: 0644
          owner: navidrome
          group: navidrome

      - dst: /var/lib/navidrome
        type: dir
        file_info:
          owner: navidrome
          group: navidrome

      - dst: /opt/navidrome/music
        type: dir
        file_info:
          owner: navidrome
          group: navidrome

    scripts:
      preinstall: "contrib/preinstall.sh"

changelog:
  # sort: asc
  filters:
    exclude:
      - "^docs:"
