services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000  # встанови свій UID:GID, якщо потрібно
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_LOGLEVEL: debug
      ND_JUKEBOX_ENABLED: "true"
      ND_JUKEBOX_ADMINONLY: "false"
      ND_CONFIGFILE: /data/navidrome.toml
      ND_MPV_CMD_TEMPLATE: "mpv --no-video --audio-device='alsa/sysdefault:CARD=U24XL' ${INPUT}"
    volumes:
      - /big/Muz:/music:ro
      - /nvme1/navidrome:/data
      - ./navidrome.toml:/data/navidrome.toml:ro
    devices:
      - /dev/snd:/dev/snd
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
