services:
  navidrome:
    build:
      context: .
      dockerfile: Dockerfile  # в тому ж каталозі
    image: navidrome-mpv
    container_name: navidrome
    user: 1000:1000  # UID:GID твого користувача
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_LOGLEVEL: debug
      ND_JUKEBOX_ENABLED: "true"
      ND_JUKEBOX_ADMINONLY: "false"
      # Цю змінну контролює navidrome для шаблону mpv
      ND_MPV_CMD_TEMPLATE: "mpv --no-video --audio-device='alsa/sysdefault:CARD=U24XL' ${INPUT}"
    volumes:
      - /big/Muz:/music:ro
      - /nvme1/navidrome:/data
      - ./navidrome.toml:/data/navidrome.toml:ro
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - 29  # або GID аудіо групи на твоїй системі
