version: "3.9"

services:
  navidrome:
    build:
      context: .
      dockerfile: Dockerfile
    image: navidrome-mpv
    container_name: navidrome
    user: "1000:1000"               # заміни за потреби
    environment:
      TZ: Europe/Kyiv
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_LOGLEVEL: debug
      ND_JUKEBOX_ENABLED: "true"
      ND_JUKEBOX_ADMINONLY: "false"
      # Підлаштуй свій ALSA-девайс (приклад нижче для USB-карти)
      ND_MPV_CMD_TEMPLATE: "mpv --no-video --audio-device='alsa/sysdefault:CARD=U24XL' ${INPUT}"
    ports:
      - "4533:4533"
    volumes:
      - /big/Muz:/music:ro           # твоя колекція
      - /nvme1/navidrome:/data       # дата/кеш
      - ./navidrome.toml:/data/navidrome.toml:ro
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - "29"                         # gid групи audio (перевір у себе)
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: jukebox-web
    depends_on:
      - navidrome
    ports:
      - "8080:80"
    # Подаємо твій HTML як index + генеруємо nginx-конфіг на льоту
    volumes:
      - ./jukebox.html:/usr/share/nginx/html/index.html:ro
    command: |
      sh -eu -c '
        cat > /etc/nginx/conf.d/default.conf <<''EOF''
        server {
          listen 80;
          server_name _;
          root /usr/share/nginx/html;
          index index.html;

          # Проксі на Navidrome під тим самим origin (щоб не було CORS)
          location /navidrome/ {
            proxy_pass http://navidrome:4533/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }

          location / {
            try_files $uri $uri/ =404;
          }
        }
        EOF
        exec nginx -g "daemon off;"
      '
    restart: unless-stopped
