// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains export wrappers for the Lyrics capability.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package lyrics

import (
	"github.com/navidrome/navidrome/plugins/pdk/go/pdk"
	"github.com/navidrome/navidrome/plugins/pdk/go/types"
)

// Deprecated: use types.ArtistRef.
type ArtistRef = types.ArtistRef

// Deprecated: use types.Track.
type TrackInfo = types.Track

// GetLyricsRequest contains the track information for lyrics lookup.
type GetLyricsRequest struct {
	Track types.Track `json:"track"`
}

// GetLyricsResponse contains the lyrics returned by the plugin.
type GetLyricsResponse struct {
	Lyrics []LyricsText `json:"lyrics"`
}

// LyricsText represents a single set of lyrics in raw text format.
// Text can be plain text or LRC format — Navidrome will parse it.
type LyricsText struct {
	Lang string `json:"lang,omitempty"`
	Text string `json:"text"`
}

// Lyrics requires all methods to be implemented.
// Lyrics provides lyrics for a given track from external sources.
type Lyrics interface {
	// GetLyrics
	GetLyrics(GetLyricsRequest) (GetLyricsResponse, error)
} // Internal implementation holders
var (
	lyricsImpl func(GetLyricsRequest) (GetLyricsResponse, error)
)

// Register registers a lyrics implementation.
// All methods are required.
func Register(impl Lyrics) {
	lyricsImpl = impl.GetLyrics
}

// NotImplementedCode is the standard return code for unimplemented functions.
// The host recognizes this and skips the plugin gracefully.
const NotImplementedCode int32 = -2

//go:wasmexport nd_lyrics_get_lyrics
func _NdLyricsGetLyrics() int32 {
	if lyricsImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input GetLyricsRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := lyricsImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}
