// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: host/artwork/artwork.proto

package artwork

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArtworkUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // Optional, 0 means original size
}

func (x *GetArtworkUrlRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetArtworkUrlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetArtworkUrlRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetArtworkUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetArtworkUrlResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetArtworkUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// go:plugin type=host version=1
type ArtworkService interface {
	GetArtistUrl(context.Context, *GetArtworkUrlRequest) (*GetArtworkUrlResponse, error)
	GetAlbumUrl(context.Context, *GetArtworkUrlRequest) (*GetArtworkUrlResponse, error)
	GetTrackUrl(context.Context, *GetArtworkUrlRequest) (*GetArtworkUrlResponse, error)
}
