// Code generated by ndpgen. DO NOT EDIT.
//
// This file provides stub implementations for non-WASM platforms.
// It allows Go plugins to compile and run tests outside of WASM,
// but the actual functionality is only available in WASM builds.
//
//go:build !wasip1

package scrobbler

// ScrobblerErrorType indicates how Navidrome should handle scrobbler errors.
type ScrobblerErrorType string

const (
	// ScrobblerErrorNone indicates no error occurred.
	ScrobblerErrorNone = "none"
	// ScrobblerErrorNotAuthorized indicates the user is not authorized.
	ScrobblerErrorNotAuthorized = "not_authorized"
	// ScrobblerErrorRetryLater indicates the operation should be retried later.
	ScrobblerErrorRetryLater = "retry_later"
	// ScrobblerErrorUnrecoverable indicates an unrecoverable error.
	ScrobblerErrorUnrecoverable = "unrecoverable"
)

// TrackInfo represents the TrackInfo data structure.
// TrackInfo contains track metadata for scrobbling.
type TrackInfo struct {
	// ID is the internal Navidrome track ID.
	ID string `json:"id"`
	// Title is the track title.
	Title string `json:"title"`
	// Album is the album name.
	Album string `json:"album"`
	// Artist is the track artist.
	Artist string `json:"artist"`
	// AlbumArtist is the album artist.
	AlbumArtist string `json:"albumArtist"`
	// Duration is the track duration in seconds.
	Duration float64 `json:"duration"`
	// TrackNumber is the track number on the album.
	TrackNumber int32 `json:"trackNumber"`
	// DiscNumber is the disc number.
	DiscNumber int32 `json:"discNumber"`
	// MBZRecordingID is the MusicBrainz recording ID.
	MBZRecordingID *string `json:"mbzRecordingId,omitempty"`
	// MBZAlbumID is the MusicBrainz album/release ID.
	MBZAlbumID *string `json:"mbzAlbumId,omitempty"`
	// MBZArtistID is the MusicBrainz artist ID.
	MBZArtistID *string `json:"mbzArtistId,omitempty"`
	// MBZReleaseGroupID is the MusicBrainz release group ID.
	MBZReleaseGroupID *string `json:"mbzReleaseGroupId,omitempty"`
	// MBZAlbumArtistID is the MusicBrainz album artist ID.
	MBZAlbumArtistID *string `json:"mbzAlbumArtistId,omitempty"`
	// MBZReleaseTrackID is the MusicBrainz release track ID.
	MBZReleaseTrackID *string `json:"mbzReleaseTrackId,omitempty"`
}

// AuthInput represents the AuthInput data structure.
// AuthInput is the input for authorization check.
type AuthInput struct {
	// UserID is the internal Navidrome user ID.
	UserID string `json:"userId"`
	// Username is the username of the user.
	Username string `json:"username"`
}

// AuthOutput represents the AuthOutput data structure.
// AuthOutput is the output for authorization check.
type AuthOutput struct {
	// Authorized indicates whether the user is authorized to scrobble.
	Authorized bool `json:"authorized"`
}

// NowPlayingInput represents the NowPlayingInput data structure.
// NowPlayingInput is the input for now playing notification.
type NowPlayingInput struct {
	// UserID is the internal Navidrome user ID.
	UserID string `json:"userId"`
	// Username is the username of the user.
	Username string `json:"username"`
	// Track is the track currently playing.
	Track TrackInfo `json:"track"`
	// Position is the current playback position in seconds.
	Position int32 `json:"position"`
}

// ScrobblerOutput represents the ScrobblerOutput data structure.
// ScrobblerOutput is the output for scrobbler operations.
type ScrobblerOutput struct {
	// Error is the error message if the operation failed.
	Error *string `json:"error,omitempty"`
	// ErrorType indicates how Navidrome should handle the error.
	ErrorType *ScrobblerErrorType `json:"errorType,omitempty"`
}

// ScrobbleInput represents the ScrobbleInput data structure.
// ScrobbleInput is the input for submitting a scrobble.
type ScrobbleInput struct {
	// UserID is the internal Navidrome user ID.
	UserID string `json:"userId"`
	// Username is the username of the user.
	Username string `json:"username"`
	// Track is the track that was played.
	Track TrackInfo `json:"track"`
	// Timestamp is the Unix timestamp when the track started playing.
	Timestamp int64 `json:"timestamp"`
}

// Scrobbler requires all methods to be implemented.
// Scrobbler provides scrobbling functionality to external services.
// This capability allows plugins to submit listening history to services like Last.fm,
// ListenBrainz, or custom scrobbling backends.
//
// All methods are required - plugins implementing this capability must provide
// all three functions: IsAuthorized, NowPlaying, and Scrobble.
type Scrobbler interface {
	// IsAuthorized - IsAuthorized checks if a user is authorized to scrobble to this service.
	IsAuthorized(AuthInput) (AuthOutput, error)
	// NowPlaying - NowPlaying sends a now playing notification to the scrobbling service.
	NowPlaying(NowPlayingInput) (ScrobblerOutput, error)
	// Scrobble - Scrobble submits a completed scrobble to the scrobbling service.
	Scrobble(ScrobbleInput) (ScrobblerOutput, error)
}

// NotImplementedCode is the standard return code for unimplemented functions.
const NotImplementedCode int32 = -2

// Register is a no-op on non-WASM platforms.
// This stub allows code to compile outside of WASM.
func Register(_ Scrobbler) {}
