// THIS FILE WAS GENERATED BY `xtp-go-bindgen`. DO NOT EDIT.
package main

import (
	pdk "github.com/extism/go-pdk"
)

//export nd_websocket_on_binary_message
func _NdWebsocketOnBinaryMessage() int32 {
	var err error
	_ = err
	pdk.Log(pdk.LogDebug, "NdWebsocketOnBinaryMessage: getting JSON input")
	var input OnBinaryMessageInput
	err = pdk.InputJSON(&input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnBinaryMessage: calling implementation function")
	output, err := NdWebsocketOnBinaryMessage(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnBinaryMessage: setting JSON output")
	err = pdk.OutputJSON(output)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnBinaryMessage: returning")
	return 0
}

//export nd_websocket_on_close
func _NdWebsocketOnClose() int32 {
	var err error
	_ = err
	pdk.Log(pdk.LogDebug, "NdWebsocketOnClose: getting JSON input")
	var input OnCloseInput
	err = pdk.InputJSON(&input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnClose: calling implementation function")
	output, err := NdWebsocketOnClose(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnClose: setting JSON output")
	err = pdk.OutputJSON(output)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnClose: returning")
	return 0
}

//export nd_websocket_on_error
func _NdWebsocketOnError() int32 {
	var err error
	_ = err
	pdk.Log(pdk.LogDebug, "NdWebsocketOnError: getting JSON input")
	var input OnErrorInput
	err = pdk.InputJSON(&input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnError: calling implementation function")
	output, err := NdWebsocketOnError(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnError: setting JSON output")
	err = pdk.OutputJSON(output)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnError: returning")
	return 0
}

//export nd_websocket_on_text_message
func _NdWebsocketOnTextMessage() int32 {
	var err error
	_ = err
	pdk.Log(pdk.LogDebug, "NdWebsocketOnTextMessage: getting JSON input")
	var input OnTextMessageInput
	err = pdk.InputJSON(&input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnTextMessage: calling implementation function")
	output, err := NdWebsocketOnTextMessage(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnTextMessage: setting JSON output")
	err = pdk.OutputJSON(output)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	pdk.Log(pdk.LogDebug, "NdWebsocketOnTextMessage: returning")
	return 0
}

// Input provided when a binary message is received
type OnBinaryMessageInput struct {
	// The unique identifier for the WebSocket connection that received the message.
	ConnectionId string `json:"connection_id"`
	// The binary data received from the WebSocket, encoded as base64.
	Data string `json:"data"`
}

// Output from the binary message handler
type OnBinaryMessageOutput struct {
	// Error message if the callback failed. Empty or null indicates success.
	Error *string `json:"error,omitempty"`
}

// Input provided when a WebSocket connection is closed
type OnCloseInput struct {
	// The WebSocket close status code (e.g., 1000 for normal closure,
	// 1001 for going away, 1006 for abnormal closure).
	Code int32 `json:"code"`
	// The unique identifier for the WebSocket connection that was closed.
	ConnectionId string `json:"connection_id"`
	// The human-readable reason for the connection closure, if provided.
	Reason string `json:"reason"`
}

// Output from the close handler
type OnCloseOutput struct {
	// Error message if the callback failed. Empty or null indicates success.
	Error *string `json:"error,omitempty"`
}

// Input provided when an error occurs on a WebSocket connection
type OnErrorInput struct {
	// The unique identifier for the WebSocket connection where the error occurred.
	ConnectionId string `json:"connection_id"`
	// The error message describing what went wrong.
	Error string `json:"error"`
}

// Output from the error handler
type OnErrorOutput struct {
	// Error message if the callback failed. Empty or null indicates success.
	Error *string `json:"error,omitempty"`
}

// Input provided when a text message is received
type OnTextMessageInput struct {
	// The unique identifier for the WebSocket connection that received the message.
	ConnectionId string `json:"connection_id"`
	// The text message content received from the WebSocket.
	Message string `json:"message"`
}

// Output from the text message handler
type OnTextMessageOutput struct {
	// Error message if the callback failed. Empty or null indicates success.
	Error *string `json:"error,omitempty"`
}
