// Code generated by ndpgen. DO NOT EDIT.

package host

import (
	"context"
	"encoding/json"

	extism "github.com/extism/go-sdk"
)

// HttpClientDoRequest is the request type for HttpClient.Do.
type HttpClientDoRequest struct {
	Request HttpRequest `json:"request"`
}

// HttpClientDoResponse is the response type for HttpClient.Do.
type HttpClientDoResponse struct {
	Result *HttpResponse `json:"result,omitempty"`
	Error  string        `json:"error,omitempty"`
}

// RegisterHttpClientHostFunctions registers HttpClient service host functions.
// The returned host functions should be added to the plugin's configuration.
func RegisterHttpClientHostFunctions(service HttpClientService) []extism.HostFunction {
	return []extism.HostFunction{
		newHttpClientDoHostFunction(service),
	}
}

func newHttpClientDoHostFunction(service HttpClientService) extism.HostFunction {
	return extism.NewHostFunctionWithStack(
		"httpclient_do",
		func(ctx context.Context, p *extism.CurrentPlugin, stack []uint64) {
			// Read JSON request from plugin memory
			reqBytes, err := p.ReadBytes(stack[0])
			if err != nil {
				httpclientWriteError(p, stack, err)
				return
			}
			var req HttpClientDoRequest
			if err := json.Unmarshal(reqBytes, &req); err != nil {
				httpclientWriteError(p, stack, err)
				return
			}

			// Call the service method
			result, svcErr := service.Do(ctx, req.Request)
			if svcErr != nil {
				httpclientWriteError(p, stack, svcErr)
				return
			}

			// Write JSON response to plugin memory
			resp := HttpClientDoResponse{
				Result: result,
			}
			httpclientWriteResponse(p, stack, resp)
		},
		[]extism.ValueType{extism.ValueTypePTR},
		[]extism.ValueType{extism.ValueTypePTR},
	)
}

// httpclientWriteResponse writes a JSON response to plugin memory.
func httpclientWriteResponse(p *extism.CurrentPlugin, stack []uint64, resp any) {
	respBytes, err := json.Marshal(resp)
	if err != nil {
		httpclientWriteError(p, stack, err)
		return
	}
	respPtr, err := p.WriteBytes(respBytes)
	if err != nil {
		stack[0] = 0
		return
	}
	stack[0] = respPtr
}

// httpclientWriteError writes an error response to plugin memory.
func httpclientWriteError(p *extism.CurrentPlugin, stack []uint64, err error) {
	errResp := struct {
		Error string `json:"error"`
	}{Error: err.Error()}
	respBytes, _ := json.Marshal(errResp)
	respPtr, _ := p.WriteBytes(respBytes)
	stack[0] = respPtr
}
