// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains stub implementations for non-WASM builds.
// These stubs allow IDE support and compilation on non-WASM platforms.
// They panic at runtime since host functions are only available in WASM plugins.
//
//go:build !wasip1

package host

// KVStoreSet is a stub that panics on non-WASM platforms.
// Set stores a byte value with the given key.
//
// Parameters:
//   - key: The storage key (max 256 bytes, UTF-8)
//   - value: The byte slice to store
//
// Returns an error if the storage limit would be exceeded or the operation fails.
func KVStoreSet(key string, value []byte) error {
	panic("host: KVStoreSet is only available in WASM plugins")
}

// KVStoreGet is a stub that panics on non-WASM platforms.
// Get retrieves a byte value from storage.
//
// Parameters:
//   - key: The storage key
//
// Returns the value and whether the key exists.
func KVStoreGet(key string) ([]byte, bool, error) {
	panic("host: KVStoreGet is only available in WASM plugins")
}

// KVStoreDelete is a stub that panics on non-WASM platforms.
// Delete removes a value from storage.
//
// Parameters:
//   - key: The storage key
//
// Returns an error if the operation fails. Does not return an error if the key doesn't exist.
func KVStoreDelete(key string) error {
	panic("host: KVStoreDelete is only available in WASM plugins")
}

// KVStoreHas is a stub that panics on non-WASM platforms.
// Has checks if a key exists in storage.
//
// Parameters:
//   - key: The storage key
//
// Returns true if the key exists.
func KVStoreHas(key string) (bool, error) {
	panic("host: KVStoreHas is only available in WASM plugins")
}

// KVStoreList is a stub that panics on non-WASM platforms.
// List returns all keys matching the given prefix.
//
// Parameters:
//   - prefix: Key prefix to filter by (empty string returns all keys)
//
// Returns a slice of matching keys.
func KVStoreList(prefix string) ([]string, error) {
	panic("host: KVStoreList is only available in WASM plugins")
}

// KVStoreGetStorageUsed is a stub that panics on non-WASM platforms.
// GetStorageUsed returns the total storage used by this plugin in bytes.
func KVStoreGetStorageUsed() (int64, error) {
	panic("host: KVStoreGetStorageUsed is only available in WASM plugins")
}
