// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains stub implementations for non-WASM builds.
// These stubs allow IDE support and compilation on non-WASM platforms.
// They panic at runtime since host functions are only available in WASM plugins.
//
//go:build !wasip1

package host

// WebSocketConnectRequest is the request type for WebSocket.Connect.
type WebSocketConnectRequest struct {
	Url          string            `json:"url"`
	Headers      map[string]string `json:"headers"`
	ConnectionID string            `json:"connectionId"`
}

// WebSocketConnectResponse is the response type for WebSocket.Connect.
type WebSocketConnectResponse struct {
	NewConnectionID string `json:"newConnectionId,omitempty"`
	Error           string `json:"error,omitempty"`
}

// WebSocketSendTextRequest is the request type for WebSocket.SendText.
type WebSocketSendTextRequest struct {
	ConnectionID string `json:"connectionId"`
	Message      string `json:"message"`
}

// WebSocketSendBinaryRequest is the request type for WebSocket.SendBinary.
type WebSocketSendBinaryRequest struct {
	ConnectionID string `json:"connectionId"`
	Data         []byte `json:"data"`
}

// WebSocketCloseConnectionRequest is the request type for WebSocket.CloseConnection.
type WebSocketCloseConnectionRequest struct {
	ConnectionID string `json:"connectionId"`
	Code         int32  `json:"code"`
	Reason       string `json:"reason"`
}

// WebSocketConnect is a stub that panics on non-WASM platforms.
// Connect establishes a WebSocket connection to the specified URL.
//
// Plugins that use this function must also implement the WebSocketCallback capability
// to receive incoming messages and connection events.
//
// Parameters:
//   - url: The WebSocket URL to connect to (ws:// or wss://)
//   - headers: Optional HTTP headers to include in the handshake request
//   - connectionID: Optional unique identifier for the connection. If empty, one will be generated
//
// Returns the connection ID that can be used to send messages or close the connection,
// or an error if the connection fails.
func WebSocketConnect(url string, headers map[string]string, connectionID string) (*WebSocketConnectResponse, error) {
	panic("host: WebSocketConnect is only available in WASM plugins")
}

// WebSocketSendText is a stub that panics on non-WASM platforms.
// SendText sends a text message over an established WebSocket connection.
//
// Parameters:
//   - connectionID: The connection identifier returned by Connect
//   - message: The text message to send
//
// Returns an error if the connection is not found or if sending fails.
func WebSocketSendText(connectionID string, message string) error {
	panic("host: WebSocketSendText is only available in WASM plugins")
}

// WebSocketSendBinary is a stub that panics on non-WASM platforms.
// SendBinary sends binary data over an established WebSocket connection.
//
// Parameters:
//   - connectionID: The connection identifier returned by Connect
//   - data: The binary data to send
//
// Returns an error if the connection is not found or if sending fails.
func WebSocketSendBinary(connectionID string, data []byte) error {
	panic("host: WebSocketSendBinary is only available in WASM plugins")
}

// WebSocketCloseConnection is a stub that panics on non-WASM platforms.
// CloseConnection gracefully closes a WebSocket connection.
//
// Parameters:
//   - connectionID: The connection identifier returned by Connect
//   - code: WebSocket close status code (e.g., 1000 for normal closure)
//   - reason: Optional human-readable reason for closing
//
// Returns an error if the connection is not found or if closing fails.
func WebSocketCloseConnection(connectionID string, code int32, reason string) error {
	panic("host: WebSocketCloseConnection is only available in WASM plugins")
}
