// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains stub implementations for non-WASM builds.
// These stubs allow IDE support and compilation on non-WASM platforms.
// They panic at runtime since host functions are only available in WASM plugins.
//
//go:build !wasip1

package host

// Library represents the Library data structure.
// Library represents a music library with metadata.
type Library struct {
	ID            int32   `json:"id"`
	Name          string  `json:"name"`
	Path          string  `json:"path"`
	MountPoint    string  `json:"mountPoint"`
	LastScanAt    int64   `json:"lastScanAt"`
	TotalSongs    int32   `json:"totalSongs"`
	TotalAlbums   int32   `json:"totalAlbums"`
	TotalArtists  int32   `json:"totalArtists"`
	TotalSize     int64   `json:"totalSize"`
	TotalDuration float64 `json:"totalDuration"`
}

// LibraryGetLibrary is a stub that panics on non-WASM platforms.
// GetLibrary retrieves metadata for a specific library by ID.
//
// Parameters:
//   - id: The library's unique identifier
//
// Returns the library metadata, or an error if the library is not found.
func LibraryGetLibrary(id int32) (*Library, error) {
	panic("host: LibraryGetLibrary is only available in WASM plugins")
}

// LibraryGetAllLibraries is a stub that panics on non-WASM platforms.
// GetAllLibraries retrieves metadata for all configured libraries.
//
// Returns a slice of all libraries with their metadata.
func LibraryGetAllLibraries() ([]Library, error) {
	panic("host: LibraryGetAllLibraries is only available in WASM plugins")
}
