// Code generated by hostgen. DO NOT EDIT.
//
// This file contains stub implementations for non-WASM builds.
// These stubs allow IDE support and compilation on non-WASM platforms.
// They panic at runtime since host functions are only available in WASM plugins.
//
//go:build !wasip1

package ndhost

// SchedulerScheduleOneTimeRequest is the request type for Scheduler.ScheduleOneTime.
type SchedulerScheduleOneTimeRequest struct {
	DelaySeconds int32  `json:"delaySeconds"`
	Payload      string `json:"payload"`
	ScheduleID   string `json:"scheduleId"`
}

// SchedulerScheduleOneTimeResponse is the response type for Scheduler.ScheduleOneTime.
type SchedulerScheduleOneTimeResponse struct {
	NewScheduleID string `json:"newScheduleId,omitempty"`
	Error         string `json:"error,omitempty"`
}

// SchedulerScheduleRecurringRequest is the request type for Scheduler.ScheduleRecurring.
type SchedulerScheduleRecurringRequest struct {
	CronExpression string `json:"cronExpression"`
	Payload        string `json:"payload"`
	ScheduleID     string `json:"scheduleId"`
}

// SchedulerScheduleRecurringResponse is the response type for Scheduler.ScheduleRecurring.
type SchedulerScheduleRecurringResponse struct {
	NewScheduleID string `json:"newScheduleId,omitempty"`
	Error         string `json:"error,omitempty"`
}

// SchedulerCancelScheduleRequest is the request type for Scheduler.CancelSchedule.
type SchedulerCancelScheduleRequest struct {
	ScheduleID string `json:"scheduleId"`
}

// SchedulerCancelScheduleResponse is the response type for Scheduler.CancelSchedule.
type SchedulerCancelScheduleResponse struct {
	Error string `json:"error,omitempty"`
}

// SchedulerScheduleOneTime is a stub that panics on non-WASM platforms.
// ScheduleOneTime schedules a one-time event to be triggered after the specified delay.
// Plugins that use this function must also implement the SchedulerCallback capability
//
// Parameters:
//   - delaySeconds: Number of seconds to wait before triggering the event
//   - payload: Data to be passed to the scheduled event handler
//   - scheduleID: Optional unique identifier for the scheduled job. If empty, one will be generated
//
// Returns the schedule ID that can be used to cancel the job, or an error if scheduling fails.
func SchedulerScheduleOneTime(delaySeconds int32, payload string, scheduleID string) (*SchedulerScheduleOneTimeResponse, error) {
	panic("ndhost: SchedulerScheduleOneTime is only available in WASM plugins")
}

// SchedulerScheduleRecurring is a stub that panics on non-WASM platforms.
// ScheduleRecurring schedules a recurring event using a cron expression.
// Plugins that use this function must also implement the SchedulerCallback capability
//
// Parameters:
//   - cronExpression: Standard cron format expression (e.g., "0 0 * * *" for daily at midnight)
//   - payload: Data to be passed to each scheduled event handler invocation
//   - scheduleID: Optional unique identifier for the scheduled job. If empty, one will be generated
//
// Returns the schedule ID that can be used to cancel the job, or an error if scheduling fails.
func SchedulerScheduleRecurring(cronExpression string, payload string, scheduleID string) (*SchedulerScheduleRecurringResponse, error) {
	panic("ndhost: SchedulerScheduleRecurring is only available in WASM plugins")
}

// SchedulerCancelSchedule is a stub that panics on non-WASM platforms.
// CancelSchedule cancels a scheduled job identified by its schedule ID.
//
// This works for both one-time and recurring schedules. Once cancelled, the job will not trigger
// any future events.
//
// Returns an error if the schedule ID is not found or if cancellation fails.
func SchedulerCancelSchedule(scheduleID string) (*SchedulerCancelScheduleResponse, error) {
	panic("ndhost: SchedulerCancelSchedule is only available in WASM plugins")
}
