// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: host/subsonicapi/subsonicapi.proto

package subsonicapi

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CallRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json  string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty if operation failed
}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CallResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// go:plugin type=host version=1
type SubsonicAPIService interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
}
