// Code generated by ndpgen. DO NOT EDIT.
//
// This file provides stub implementations for non-WASM platforms.
// It allows Go plugins to compile and run tests outside of WASM,
// but the actual functionality is only available in WASM builds.
//
//go:build !wasip1

package metadata

// ArtistMBIDInput is the input for GetArtistMBID.
type ArtistMBIDInput struct {
	// ID is the internal Navidrome artist ID.
	ID string `json:"id"`
	// Name is the artist name.
	Name string `json:"name"`
}

// ArtistURLOutput is the output for GetArtistURL.
type ArtistURLOutput struct {
	// URL is the external URL for the artist.
	URL string `json:"url"`
}

// AlbumInfoOutput is the output for GetAlbumInfo.
type AlbumInfoOutput struct {
	// Name is the album name.
	Name string `json:"name"`
	// MBID is the MusicBrainz ID for the album.
	MBID string `json:"mbid"`
	// Description is the album description/notes.
	Description string `json:"description"`
	// URL is the external URL for the album.
	URL string `json:"url"`
}

// AlbumImagesOutput is the output for GetAlbumImages.
type AlbumImagesOutput struct {
	// Images is the list of album images.
	Images []ImageInfo `json:"images"`
}

// SongRef is a reference to a song with name and optional MBID.
type SongRef struct {
	// Name is the song name.
	Name string `json:"name"`
	// MBID is the MusicBrainz ID for the song.
	MBID *string `json:"mbid,omitempty"`
}

// ImageInfo represents an image with URL and size.
type ImageInfo struct {
	// URL is the URL of the image.
	URL string `json:"url"`
	// Size is the size of the image in pixels (width or height).
	Size int32 `json:"size"`
}

// ArtistBiographyOutput is the output for GetArtistBiography.
type ArtistBiographyOutput struct {
	// Biography is the artist biography text.
	Biography string `json:"biography"`
}

// SimilarArtistsOutput is the output for GetSimilarArtists.
type SimilarArtistsOutput struct {
	// Artists is the list of similar artists.
	Artists []ArtistRef `json:"artists"`
}

// TopSongsInput is the input for GetArtistTopSongs.
type TopSongsInput struct {
	// ID is the internal Navidrome artist ID.
	ID string `json:"id"`
	// Name is the artist name.
	Name string `json:"name"`
	// MBID is the MusicBrainz ID for the artist (if known).
	MBID *string `json:"mbid,omitempty"`
	// Count is the maximum number of top songs to return.
	Count int32 `json:"count"`
}

// TopSongsOutput is the output for GetArtistTopSongs.
type TopSongsOutput struct {
	// Songs is the list of top songs.
	Songs []SongRef `json:"songs"`
}

// ArtistRef is a reference to an artist with name and optional MBID.
type ArtistRef struct {
	// Name is the artist name.
	Name string `json:"name"`
	// MBID is the MusicBrainz ID for the artist.
	MBID *string `json:"mbid,omitempty"`
}

// ArtistImagesOutput is the output for GetArtistImages.
type ArtistImagesOutput struct {
	// Images is the list of artist images.
	Images []ImageInfo `json:"images"`
}

// ArtistMBIDOutput is the output for GetArtistMBID.
type ArtistMBIDOutput struct {
	// MBID is the MusicBrainz ID for the artist.
	MBID string `json:"mbid"`
}

// ArtistInput is the common input for artist-related functions.
type ArtistInput struct {
	// ID is the internal Navidrome artist ID.
	ID string `json:"id"`
	// Name is the artist name.
	Name string `json:"name"`
	// MBID is the MusicBrainz ID for the artist (if known).
	MBID *string `json:"mbid,omitempty"`
}

// SimilarArtistsInput is the input for GetSimilarArtists.
type SimilarArtistsInput struct {
	// ID is the internal Navidrome artist ID.
	ID string `json:"id"`
	// Name is the artist name.
	Name string `json:"name"`
	// MBID is the MusicBrainz ID for the artist (if known).
	MBID *string `json:"mbid,omitempty"`
	// Limit is the maximum number of similar artists to return.
	Limit int32 `json:"limit"`
}

// AlbumInput is the common input for album-related functions.
type AlbumInput struct {
	// Name is the album name.
	Name string `json:"name"`
	// Artist is the album artist name.
	Artist string `json:"artist"`
	// MBID is the MusicBrainz ID for the album (if known).
	MBID *string `json:"mbid,omitempty"`
}

// Metadata is the marker interface for metadata plugins.
// Implement one or more of the provider interfaces below.
// MetadataAgent provides artist and album metadata retrieval.
// This capability allows plugins to provide external metadata for artists and albums,
// such as biographies, images, similar artists, and top songs.
//
// Plugins implementing this capability can choose which methods to implement.
// Each method is optional - plugins only need to provide the functionality they support.
type Metadata interface{}

// ArtistMBIDProvider provides the GetArtistMBID function.
type ArtistMBIDProvider interface {
	GetArtistMBID(ArtistMBIDInput) (ArtistMBIDOutput, error)
}

// ArtistURLProvider provides the GetArtistURL function.
type ArtistURLProvider interface {
	GetArtistURL(ArtistInput) (ArtistURLOutput, error)
}

// ArtistBiographyProvider provides the GetArtistBiography function.
type ArtistBiographyProvider interface {
	GetArtistBiography(ArtistInput) (ArtistBiographyOutput, error)
}

// SimilarArtistsProvider provides the GetSimilarArtists function.
type SimilarArtistsProvider interface {
	GetSimilarArtists(SimilarArtistsInput) (SimilarArtistsOutput, error)
}

// ArtistImagesProvider provides the GetArtistImages function.
type ArtistImagesProvider interface {
	GetArtistImages(ArtistInput) (ArtistImagesOutput, error)
}

// ArtistTopSongsProvider provides the GetArtistTopSongs function.
type ArtistTopSongsProvider interface {
	GetArtistTopSongs(TopSongsInput) (TopSongsOutput, error)
}

// AlbumInfoProvider provides the GetAlbumInfo function.
type AlbumInfoProvider interface {
	GetAlbumInfo(AlbumInput) (AlbumInfoOutput, error)
}

// AlbumImagesProvider provides the GetAlbumImages function.
type AlbumImagesProvider interface {
	GetAlbumImages(AlbumInput) (AlbumImagesOutput, error)
}

// NotImplementedCode is the standard return code for unimplemented functions.
const NotImplementedCode int32 = -2

// Register is a no-op on non-WASM platforms.
// This stub allows code to compile outside of WASM.
func Register(_ Metadata) {}
